name: Run Azure Login with OpenID Connect and PowerShell
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
      runs-on: ubuntu-latest
      environment: Dev
      steps:
        - name: Installing Azure CLi
          uses: elstudio/action-install-azure-cli@v1
          
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
           creds: ${{secrets.AZURE_CREDENTIALS}}
        - name: 'Run az commands'
          run: |
            az account show
            az group list
            pwd     
