name: AzureARM Deploy

on: push
env: 
  id-token: write
jobs:
  Deploy:
   runs-on: ubuntu-latest
   environment: dev
   steps:
     - uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
        
     - name: Checkout source code 
       uses: actions/checkout@v2
     
     - name: Deploy ARM Template
       uses: azure/arm-deploy@v1
       with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./ARMTemplates/My-LogicApp.json
          parameters: ./ARMTemplates/parameters.json
